structure_manifest: "kahraman_analysis/kahraman_af_structure_manifest.csv"
output_dir: "kahraman_alphacognate_cathaf"
domains: "cath-alphafold"
cognate_match: true
domain_match: true
top_ranked: false