version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: postgresdb
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD_FILE=/run/secrets/pg_db_pass
      - POSTGRES_USER=admin
      - POSTGRES_DB=postgres
    secrets:
      - pg_db_pass
    networks:
      - app-network

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: 'teste@teste.com'
      PGADMIN_DEFAULT_PASSWORD: 'teste'
    ports:
      - "16543:80"
    volumes:
      - ./servers.json:/pgadmin4/servers.json
    networks:
      - app-network

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    depends_on:
      - postgres
    networks:
      - app-network

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile.prod
    ports:
      - "5173:5173"
      - "80:80"
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: nginx-file-server
    ports:
      - "8080:80"
    volumes:
      - ./cif-files:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - app-network
    restart: always

secrets:
  pg_db_pass:
    file: credentials/pg_db_pass.txt

volumes:
  postgres-data:

networks:
  app-network:
    driver: bridge