version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: postgresdb
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD_FILE=/run/secrets/pg_db_pass
      - POSTGRES_USER=admin
      - POSTGRES_DB=postgres
    secrets:
      - pg_db_pass
    networks:
      - app-network

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./backend/cif-files:/app/cif-files
    depends_on:
      - postgres
    networks:
      - app-network

  # frontend:
  #   build:
  #     context: .
  #     dockerfile: frontend/Dockerfile.prod
  #   ports:
  #     - "5173:5173"
  #     - "80:80"
  #   networks:
  #     - app-network

secrets:
  pg_db_pass:
    file: credentials/pg_db_pass.txt

volumes:
  postgres-data:

networks:
  app-network:
    driver: bridge