services:
  postgres:
    image: postgres:15
    container_name: postgresdb
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD_FILE=/run/secrets/pg_db_pass
      - POSTGRES_USER=admin
      - POSTGRES_DB=postgres
    secrets:
      - pg_db_pass
    networks:
      - postgres-db-network
  pgadmin:
    image: dpage/pgadmin4
    environment:
        PGADMIN_DEFAULT_EMAIL: 'teste@teste.com'
        PGADMIN_DEFAULT_PASSWORD: 'teste'
    ports:
        - 16543:80
    volumes:
        - ./servers.json:/pgadmin4/servers.json
    networks:
        - postgres-db-network

secrets:
  pg_db_pass:
    file: credentials/pg_db_pass.txt

volumes:
  postgres-data:

networks:
    postgres-db-network:
        driver: bridge